apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/postgresql/data
