version: "3.8"

services:
  web:
    platform: linux/amd64
    image: nginx:1.21.6
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/files/nginx.conf:/tmp/nginx.conf
    env_file: ./.env
    command: >
      sh -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf &&
             nginx -g 'daemon off;'"
    depends_on:
      - backend

  db:
    platform: linux/amd64
    image: postgres:14.1
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    platform: linux/amd64
    image: mapstack/backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./backend:/code
    env_file: ./.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: {}