name: mapstack
channels:
  - conda-forge

dependencies:
  - celery=5.2.3
  - django-celery-results=2.2.0
  - django-cors-headers=3.11.0
  - django-storages[azure]=1.12.3
  - Django=4.0.1
  - djangorestframework=3.13.1
  - docker-compose
  - environs=9.4.0
  - gunicorn=20.1.0
  - make
  - psycopg2=2.9.1
  - python=3.9

  # docs
  - pydata-sphinx-theme
  - sphinx

  # testing
  - coverage=6.3.1
  - flake8=4.0.1
  - locust=2.8.2
  - pytest-django=4.5.2
  - pytest-monitor=1.6.3
  - pytest-profiling=1.7.0
  - pytest=7.0.1

  # pip dependencies
  - pip
  - pip:
    - django-redis==5.2.0
    - djangorestframework-simplejwt==5.0.0
    - redis==4.1.2
    # testing
    - django-silk==4.2.0
    - factory-boy==3.2.1
