apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - command:
            - /bin/sh
            - '-c'
          args:
            - |
              python manage.py migrate --no-input;
              python manage.py collectstatic --noinput;
              gunicorn --bind 0.0.0.0:8000 config.wsgi;
          name: backend
          image: mapstackregistry.azurecr.io/backend:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_SERVER_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: REDIS_SERVER_ADDR
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CELERY_BROKER_URL
            - name: BACKEND_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: BACKEND_SECRET_KEY
            - name: BACKEND_ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: BACKEND_ALLOWED_HOSTS
            - name: BACKEND_DEBUG
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: BACKEND_DEBUG
            - name: AZURE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AZURE_ACCOUNT_NAME
            - name: AZURE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AZURE_ACCOUNT_KEY
            - name: AZURE_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AZURE_CONTAINER
      imagePullSecrets:
        - name: registry
