apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  POSTGRES_HOST: database
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  CELERY_BROKER_URL: redis://redis:6379
  REDIS_SERVER_ADDR: redis:6379
  GEOSERVER_DOWNLOAD_URL: https://sourceforge.net/projects/geoserver/files/GeoServer/2.20.2/geoserver-2.20.2-war.zip/download
  GEOSERVER_INITIAL_MEMORY: "4G"
  GEOSERVER_MAXIMUM_MEMORY: "4G"
  GEOSERVER_ADMIN_PASSWORD: admin
  BACKEND_DEBUG: "false"
  BACKEND_SECRET_KEY: "*%m^(a1q0q%0j+o8le2__cssyyt20#4lta(7vscp8*v-jal1e@"
  BACKEND_ALLOWED_HOSTS: "mapstack.eastus.cloudapp.azure.com"
  AZURE_ACCOUNT_NAME: mapstackstorageaccount
  AZURE_ACCOUNT_KEY: "Y1QvxI49ca9o7hKxkMiMGKiOLUXaecTwIvysRb7TxcdTcV8xo7XkC8LQ0bX90KProgaVUldBtEJL+ASttP/2BA=="
  AZURE_CONTAINER: static
