apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  POSTGRES_HOST: null
  POSTGRES_PORT: null
  POSTGRES_DB: null
  POSTGRES_USER: null
  POSTGRES_PASSWORD: null
  BACKEND_SERVER_ADDR: null
  CELERY_BROKER_URL: null
  SILK: null
  REDIS_SERVER_ADDR: null
  GEOSERVER_SERVER_ADDR: null
  GEOSERVER_URL: null
  INITIAL_MEMORY: null
  MAXIMUM_MEMORY: null
  ADMIN_PASSWORD: null
  MAPSHADER_SERVER_ADDR: null
  DEBUG: null
  SECRET_KEY: null
  ALLOWED_HOSTS: null