apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  POSTGRES_HOST: null
  POSTGRES_PORT: null
  POSTGRES_DB: null
  POSTGRES_USER: null
  POSTGRES_PASSWORD: null
  CELERY_BROKER_URL: null
  BACKEND_SILK: null
  REDIS_SERVER_ADDR: null
  GEOSERVER_DOWNLOAD_URL: null
  GEOSERVER_INITIAL_MEMORY: null
  GEOSERVER_MAXIMUM_MEMORY: null
  GEOSERVER_ADMIN_PASSWORD: null
  BACKEND_DEBUG: null
  BACKEND_SECRET_KEY: null
  BACKEND_ALLOWED_HOSTS: null
  AZURE_ACCOUNT_NAME: null
  AZURE_ACCOUNT_KEY: null
  AZURE_CONTAINER: null
