apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - command:
            - /bin/sh
            - '-c'
          args:
            - |
              python manage.py migrate --no-input;
              python manage.py collectstatic --noinput;
              gunicorn --bind 0.0.0.0:8000 config.wsgi;
          name: backend
          image: mapstack/backend
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PORT
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_SERVER_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: REDIS_SERVER_ADDR
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CELERY_BROKER_URL
