apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: mapstack/nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_SERVER_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: BACKEND_SERVER_ADDR
            - name: GEOSERVER_SERVER_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GEOSERVER_SERVER_ADDR
            - name: MAPSHADER_SERVER_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MAPSHADER_SERVER_ADDR
